name: Playwright Tests & Chromatic

# This is an unusual job because it's triggered by deploy events rather than
# PR/push. The if condition means we only run on deployment_status events where
# the status is success, i.e., we only run after Vercel deploy has succeeded.

on:
  deployment_status:

jobs:
  playwright:
    if:
      github.event_name == 'deployment_status' && github.event.deployment_status.state ==
      'success'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
        env:
          BASE_URL: ${{ github.event.deployment_status.target_url }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30

  chromatic:
    name: Run Chromatic
    if:
      github.event_name == 'deployment_status' && github.event.deployment_status.state ==
      'success'
    needs: playwright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Download Playwright test results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: ./test-results
      - name: Run Chromatic
        run:
          npx chromatic --playwright --project-token ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          --exit-zero-on-changes
        env:
          CHROMATIC_ARCHIVE_LOCATION: ./test-results
